/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afpa.ecf.physicalregatta.view;

/**
 *
 * @author gwenole
 */
public class SailboatRegister extends javax.swing.JFrame {

    /**
     * Creates new form SailboatRegister
     */
    public SailboatRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        panFooter = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtInfo = new javax.swing.JTextField();
        panContent = new javax.swing.JPanel();
        lblSail = new javax.swing.JLabel();
        txtSail = new javax.swing.JTextField();
        lblOwner = new javax.swing.JLabel();
        cboOwner = new javax.swing.JComboBox<>();
        lblSerie = new javax.swing.JLabel();
        cboSerie = new javax.swing.JComboBox<>();
        lblClass = new javax.swing.JLabel();
        cboClass = new javax.swing.JComboBox<>();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter un voilier");
        setAutoRequestFocus(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        panFooter.setLayout(new java.awt.BorderLayout(10, 10));

        btnClose.setText("Fermer");
        panFooter.add(btnClose, java.awt.BorderLayout.CENTER);

        btnAdd.setText("Ajouter");
        panFooter.add(btnAdd, java.awt.BorderLayout.LINE_END);

        txtInfo.setEditable(false);
        txtInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtInfo.setPreferredSize(new java.awt.Dimension(505, 23));
        panFooter.add(txtInfo, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panFooter, java.awt.BorderLayout.PAGE_END);

        panContent.setBorder(javax.swing.BorderFactory.createTitledBorder("Saisissez les informations ci-dessous"));
        panContent.setMinimumSize(new java.awt.Dimension(536, 62));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        panContent.setLayout(flowLayout1);

        lblSail.setText("Numéro de voile");
        lblSail.setMaximumSize(new java.awt.Dimension(150, 15));
        lblSail.setMinimumSize(new java.awt.Dimension(150, 15));
        lblSail.setPreferredSize(new java.awt.Dimension(150, 15));
        panContent.add(lblSail);

        txtSail.setToolTipText("Numéro de voile");
        txtSail.setPreferredSize(new java.awt.Dimension(350, 23));
        panContent.add(txtSail);

        lblOwner.setText("Propriétaire");
        lblOwner.setMaximumSize(new java.awt.Dimension(150, 15));
        lblOwner.setMinimumSize(new java.awt.Dimension(150, 15));
        lblOwner.setPreferredSize(new java.awt.Dimension(150, 15));
        panContent.add(lblOwner);

        cboOwner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboOwner.setPreferredSize(new java.awt.Dimension(350, 25));
        panContent.add(cboOwner);

        lblSerie.setText("Série");
        lblSerie.setMaximumSize(new java.awt.Dimension(150, 15));
        lblSerie.setMinimumSize(new java.awt.Dimension(150, 15));
        lblSerie.setPreferredSize(new java.awt.Dimension(150, 15));
        panContent.add(lblSerie);

        cboSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSerie.setPreferredSize(new java.awt.Dimension(350, 25));
        panContent.add(cboSerie);

        lblClass.setText("Classe");
        lblClass.setMaximumSize(new java.awt.Dimension(150, 15));
        lblClass.setMinimumSize(new java.awt.Dimension(150, 15));
        lblClass.setPreferredSize(new java.awt.Dimension(150, 15));
        panContent.add(lblClass);

        cboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboClass.setPreferredSize(new java.awt.Dimension(350, 25));
        panContent.add(cboClass);

        getContentPane().add(panContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SailboatRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SailboatRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SailboatRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SailboatRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SailboatRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> cboClass;
    private javax.swing.JComboBox<String> cboOwner;
    private javax.swing.JComboBox<String> cboSerie;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblOwner;
    private javax.swing.JLabel lblSail;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JPanel panContent;
    private javax.swing.JPanel panFooter;
    private javax.swing.JTextField txtInfo;
    private javax.swing.JTextField txtSail;
    // End of variables declaration//GEN-END:variables
}
